# # -*- coding: utf-8 -*-
#
# # Form implementation generated from reading ui file 'loadwin.ui'
# #
# # Created by: PyQt5 UI code generator 5.15.4
# #
# # WARNING: Any manual changes made to this file will be lost when pyuic5 is
# # run again.  Do not edit this file unless you know what you are doing.
#

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(704, 480)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 711, 481))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.frame.setFont(font)
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("background-color: rgb(70, 130, 180);")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(130, 60, 201, 201))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("./gui/武汉理工大学_副本.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(360, 60, 201, 201))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("./gui/浙江工业职业技术学院.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setGeometry(QtCore.QRect(60, 390, 611, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(70, 360, 500, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(560, 450, 141, 31))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "正在计算数据..."))
        self.label_4.setText(_translate("Form", "designed by robot group"))
#


# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loadwin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# from PyQt5 import QtCore, QtGui, QtWidgets
#
#
# class Ui_Form(object):
#     def setupUi(self, Form):
#         Form.setObjectName("Form")
#         Form.resize(704, 480)
#         self.frame = QtWidgets.QFrame(Form)
#         self.frame.setGeometry(QtCore.QRect(0, 0, 711, 481))
#         font = QtGui.QFont()
#         font.setBold(True)
#         font.setWeight(75)
#         self.frame.setFont(font)
#         self.frame.setAutoFillBackground(False)
#         self.frame.setStyleSheet("background-color: rgb(70, 130, 180);")
#         self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
#         self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
#         self.frame.setObjectName("frame")
#         self.label = QtWidgets.QLabel(self.frame)
#         self.label.setGeometry(QtCore.QRect(150, 60, 201, 201))
#         self.label.setText("")
#         self.label.setPixmap(QtGui.QPixmap("./gui/武汉理工大学_副本.png"))
#         self.label.setScaledContents(True)
#         self.label.setObjectName("label")
#         self.label_2 = QtWidgets.QLabel(self.frame)
#         self.label_2.setGeometry(QtCore.QRect(360, 60, 201, 201))
#         self.label_2.setText("")
#         self.label_2.setPixmap(QtGui.QPixmap("./gui/浙江工业职业技术学院.png"))
#         self.label_2.setScaledContents(True)
#         self.label_2.setObjectName("label_2")
#         self.progressBar = QtWidgets.QProgressBar(self.frame)
#         self.progressBar.setGeometry(QtCore.QRect(60, 390, 611, 31))
#         font = QtGui.QFont()
#         font.setFamily("黑体")
#         font.setPointSize(10)
#         self.progressBar.setFont(font)
#         self.progressBar.setProperty("value", 24)
#         self.progressBar.setObjectName("progressBar")
#         self.label_3 = QtWidgets.QLabel(self.frame)
#         self.label_3.setGeometry(QtCore.QRect(70, 360, 500, 21))
#         font = QtGui.QFont()
#         font.setFamily("黑体")
#         font.setPointSize(12)
#         font.setBold(True)
#         font.setWeight(75)
#         self.label_3.setFont(font)
#         self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
#         self.label_3.setObjectName("label_3")
#         self.label_4 = QtWidgets.QLabel(self.frame)
#         self.label_4.setGeometry(QtCore.QRect(560, 450, 141, 31))
#         self.label_4.setObjectName("label_4")
#
#         self.retranslateUi(Form)
#         QtCore.QMetaObject.connectSlotsByName(Form)
#
#     def retranslateUi(self, Form):
#         _translate = QtCore.QCoreApplication.translate
#         Form.setWindowTitle(_translate("Form", "Form"))
#         self.label_3.setText(_translate("Form", "正在计算数据..."))
#         self.label_4.setText(_translate("Form", "designed by robot group"))

