# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo1109.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1728, 838)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setStyleSheet("")
        self.groupBox_6.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.groupBox_6)
        self.graphicsView.setEnabled(False)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.groupBox_6)
        self.graphicsView_3.setEnabled(False)
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.gridLayout.addWidget(self.graphicsView_3, 1, 0, 1, 1)
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.groupBox_6)
        self.graphicsView_2.setEnabled(False)
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.gridLayout.addWidget(self.graphicsView_2, 0, 1, 1, 1)
        self.graphicsView_4 = QtWidgets.QGraphicsView(self.groupBox_6)
        self.graphicsView_4.setEnabled(False)
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.gridLayout.addWidget(self.graphicsView_4, 1, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.horizontalLayout.addWidget(self.groupBox_6)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.graphicsView_5 = QtWidgets.QGraphicsView(self.groupBox_2)
        self.graphicsView_5.setEnabled(False)
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.verticalLayout_3.addWidget(self.graphicsView_5)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 283))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.textBrowser_9 = QtWidgets.QTextBrowser(self.groupBox_3)
        self.textBrowser_9.setObjectName("textBrowser_9")
        self.horizontalLayout_6.addWidget(self.textBrowser_9)
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        spacerItem = QtWidgets.QSpacerItem(28, 28, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.verticalLayout_12.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        spacerItem1 = QtWidgets.QSpacerItem(13, 36, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_7.addWidget(self.label_11)
        spacerItem2 = QtWidgets.QSpacerItem(13, 36, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        spacerItem3 = QtWidgets.QSpacerItem(14, 36, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        spacerItem4 = QtWidgets.QSpacerItem(13, 36, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.textBrowser_10 = QtWidgets.QTextBrowser(self.groupBox_3)
        self.textBrowser_10.setEnabled(False)
        self.textBrowser_10.setObjectName("textBrowser_10")
        self.horizontalLayout_7.addWidget(self.textBrowser_10)
        self.horizontalLayout_7.setStretch(0, 5)
        self.horizontalLayout_7.setStretch(1, 3)
        self.horizontalLayout_7.setStretch(2, 1)
        self.horizontalLayout_7.setStretch(3, 3)
        self.horizontalLayout_7.setStretch(4, 1)
        self.horizontalLayout_7.setStretch(5, 3)
        self.horizontalLayout_7.setStretch(6, 1)
        self.horizontalLayout_7.setStretch(7, 3)
        self.horizontalLayout_7.setStretch(8, 1)
        self.horizontalLayout_7.setStretch(9, 3)
        self.horizontalLayout_7.setStretch(10, 1)
        self.verticalLayout_12.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_8.addWidget(self.label_12)
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.groupBox_3)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.horizontalLayout_8.addWidget(self.textBrowser_3)
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_8.addWidget(self.label_13)
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.groupBox_3)
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.horizontalLayout_8.addWidget(self.textBrowser_4)
        self.verticalLayout_12.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_9.addWidget(self.label_14)
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.groupBox_3)
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.horizontalLayout_9.addWidget(self.textBrowser_5)
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_9.addWidget(self.label_15)
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.groupBox_3)
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.horizontalLayout_9.addWidget(self.textBrowser_6)
        self.verticalLayout_12.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_10.addWidget(self.label_16)
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.groupBox_3)
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.horizontalLayout_10.addWidget(self.textBrowser_7)
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_10.addWidget(self.label_17)
        self.textBrowser_8 = QtWidgets.QTextBrowser(self.groupBox_3)
        self.textBrowser_8.setObjectName("textBrowser_8")
        self.horizontalLayout_10.addWidget(self.textBrowser_8)
        self.verticalLayout_12.addLayout(self.horizontalLayout_10)
        self.verticalLayout_13.addLayout(self.verticalLayout_12)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.verticalLayout.setStretch(0, 8)
        self.verticalLayout.setStretch(1, 7)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(0, 8)
        self.horizontalLayout.setStretch(1, 4)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1728, 23))
        self.menubar.setStyleSheet("")
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setStyleSheet("")
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setStyleSheet("")
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.menu_5.setFont(font)
        self.menu_5.setObjectName("menu_5")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setStyleSheet("")
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.sidetool = QtWidgets.QDockWidget(MainWindow)
        self.sidetool.setMinimumSize(QtCore.QSize(281, 635))
        self.sidetool.setObjectName("sidetool")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.dockWidgetContents)
        self.textBrowser_2.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.horizontalLayout_4.addWidget(self.textBrowser_2)
        self.pushButton_16 = QtWidgets.QPushButton(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_4.addWidget(self.pushButton_16)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.pushButton_18 = QtWidgets.QPushButton(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setObjectName("pushButton_18")
        self.verticalLayout_4.addWidget(self.pushButton_18)
        self.pushButton_13 = QtWidgets.QPushButton(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setObjectName("pushButton_13")
        self.verticalLayout_4.addWidget(self.pushButton_13)
        self.pushButton_14 = QtWidgets.QPushButton(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setObjectName("pushButton_14")
        self.verticalLayout_4.addWidget(self.pushButton_14)
        self.pushButton_15 = QtWidgets.QPushButton(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setObjectName("pushButton_15")
        self.verticalLayout_4.addWidget(self.pushButton_15)
        self.verticalLayout_4.setStretch(1, 3)
        self.verticalLayout_4.setStretch(2, 2)
        self.verticalLayout_4.setStretch(3, 2)
        self.verticalLayout_4.setStretch(4, 2)
        self.verticalLayout_7.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 0, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 0, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 1, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_2.addWidget(self.pushButton_5, 1, 1, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_2)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.groupBox_4 = QtWidgets.QGroupBox(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_5.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_5.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_5.addWidget(self.pushButton_8)
        self.verticalLayout_10.addLayout(self.horizontalLayout_5)
        self.verticalLayout_5.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_3.addWidget(self.pushButton_9, 0, 0, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_3.addWidget(self.pushButton_10, 0, 1, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_3.addWidget(self.pushButton_11, 1, 0, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_3.addWidget(self.pushButton_12, 1, 1, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_3)
        self.verticalLayout_5.addWidget(self.groupBox_5)
        self.verticalLayout_5.setStretch(0, 3)
        self.verticalLayout_5.setStretch(1, 2)
        self.verticalLayout_5.setStretch(2, 3)
        self.verticalLayout_7.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_17 = QtWidgets.QPushButton(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setObjectName("pushButton_17")
        self.verticalLayout_6.addWidget(self.pushButton_17)
        self.pushButton = QtWidgets.QPushButton(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_6.addWidget(self.pushButton)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.verticalLayout_7.setStretch(0, 1)
        self.verticalLayout_7.setStretch(1, 8)
        self.verticalLayout_7.setStretch(2, 2)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.sidetool.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.sidetool)
        self.logdock = QtWidgets.QDockWidget(MainWindow)
        self.logdock.setMinimumSize(QtCore.QSize(1600, 120))
        self.logdock.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.logdock.setObjectName("logdock")
        self.dockWidgetContents_5 = QtWidgets.QWidget()
        self.dockWidgetContents_5.setObjectName("dockWidgetContents_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dockWidgetContents_5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.dockWidgetContents_5)
        self.textBrowser.setEnabled(True)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_2.addWidget(self.textBrowser)
        self.logdock.setWidget(self.dockWidgetContents_5)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.logdock)
        self.actionexit = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/退出/退出.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionexit.setIcon(icon)
        self.actionexit.setObjectName("actionexit")
        self.actionsetPicPath = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/选择图片路径/待选择.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionsetPicPath.setIcon(icon1)
        self.actionsetPicPath.setObjectName("actionsetPicPath")
        self.actionchooseTemplate = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/设置模板/样本录入.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionchooseTemplate.setIcon(icon2)
        self.actionchooseTemplate.setObjectName("actionchooseTemplate")
        self.actionsetParaments = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/参数修改/实时参数推荐.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionsetParaments.setIcon(icon3)
        self.actionsetParaments.setObjectName("actionsetParaments")
        self.actionmax = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/最大化/最大化.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionmax.setIcon(icon4)
        self.actionmax.setObjectName("actionmax")
        self.actionmin_2 = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/最小化/最小化.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionmin_2.setIcon(icon5)
        self.actionmin_2.setObjectName("actionmin_2")
        self.actionsetSavePath = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/设置保存路径/设置保存路径.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(":/保存/保存.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionsetSavePath.setIcon(icon6)
        self.actionsetSavePath.setObjectName("actionsetSavePath")
        self.actionipconfig = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/IP配置/IP.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionipconfig.setIcon(icon7)
        self.actionipconfig.setObjectName("actionipconfig")
        self.actionhelp_2 = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/帮助/帮 助.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionhelp_2.setIcon(icon8)
        self.actionhelp_2.setObjectName("actionhelp_2")
        self.actionabout_2 = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/关于/关于.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionabout_2.setIcon(icon9)
        self.actionabout_2.setObjectName("actionabout_2")
        self.actionsave = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/保存/保存.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon10.addPixmap(QtGui.QPixmap(":/保存/保存.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionsave.setIcon(icon10)
        self.actionsave.setObjectName("actionsave")
        self.actionstart = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/开始/开始.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionstart.setIcon(icon11)
        self.actionstart.setObjectName("actionstart")
        self.actionstop = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/暂停/暂停.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionstop.setIcon(icon12)
        self.actionstop.setObjectName("actionstop")
        self.actionsetValue = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/设置阈值/阈值.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionsetValue.setIcon(icon13)
        self.actionsetValue.setObjectName("actionsetValue")
        self.actiondelay_time = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/延时/延时.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actiondelay_time.setIcon(icon14)
        self.actiondelay_time.setObjectName("actiondelay_time")
        self.actionmethod_side = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/侧面检测方法/检测方法.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon15.addPixmap(QtGui.QPixmap(":/选择图片路径/待选择.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionmethod_side.setIcon(icon15)
        self.actionmethod_side.setObjectName("actionmethod_side")
        self.actiontools = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/工具/工具.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon16.addPixmap(QtGui.QPixmap(":/选择图片路径/待选择.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actiontools.setIcon(icon16)
        self.actiontools.setObjectName("actiontools")
        self.actionset_yzFf_duan = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/设置端面方法和阈值/圆.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionset_yzFf_duan.setIcon(icon17)
        self.actionset_yzFf_duan.setObjectName("actionset_yzFf_duan")
        self.actionset_yzFf_ce = QtWidgets.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/设置侧面阈值分割方法和阈值/tx-长方形.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionset_yzFf_ce.setIcon(icon18)
        self.actionset_yzFf_ce.setObjectName("actionset_yzFf_ce")
        self.menu.addAction(self.actionexit)
        self.menu.addAction(self.actionsave)
        self.menu_2.addAction(self.actionsetPicPath)
        self.menu_2.addAction(self.actionchooseTemplate)
        self.menu_2.addAction(self.actionsetParaments)
        self.menu_2.addAction(self.actionsetSavePath)
        self.menu_2.addAction(self.actionstart)
        self.menu_2.addAction(self.actionstop)
        self.menu_2.addAction(self.actionsetValue)
        self.menu_2.addAction(self.actiondelay_time)
        self.menu_2.addAction(self.actionset_yzFf_duan)
        self.menu_2.addAction(self.actionset_yzFf_ce)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.actionmax)
        self.menu_3.addAction(self.actionmin_2)
        self.menu_4.addAction(self.actionipconfig)
        self.menu_5.addAction(self.actionhelp_2)
        self.menu_5.addAction(self.actionabout_2)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_5.menuAction())
        self.toolBar.addAction(self.actionsave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionexit)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionsetSavePath)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionsetPicPath)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionchooseTemplate)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actiondelay_time)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionset_yzFf_duan)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionset_yzFf_ce)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actiontools)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionsetParaments)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionipconfig)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionstart)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionstop)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionhelp_2)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionabout_2)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        # self.actionstart.triggered.connect(MainWindow.start_system)
        # self.actionabout_2.triggered.connect(MainWindow.about)
        # self.actionchooseTemplate.triggered.connect(MainWindow.get_template)
        # self.actionexit.triggered.connect(MainWindow.exit)
        # self.actionhelp_2.triggered.connect(MainWindow.help)
        # self.actionipconfig.triggered.connect(MainWindow.find_plc)
        # self.actionmax.triggered.connect(MainWindow.max)
        # self.actionmin_2.triggered.connect(MainWindow.max)
        # self.actionsave.triggered.connect(MainWindow.save_computer_result)
        # self.actionsetSavePath.triggered.connect(MainWindow.set_save_path)
        # self.actionsetPicPath.triggered.connect(MainWindow.set_pic_path)
        # self.actionsetParaments.triggered.connect(MainWindow.set_paraments)
        # self.actionstop.triggered.connect(MainWindow.stop_system)
        # self.actionsetValue.triggered.connect(MainWindow.set_Value)
        # self.actiondelay_time.triggered.connect(MainWindow.set_delay_time)
        # self.actionmethod_side.triggered.connect(MainWindow.set_side_method)
        # self.actiontools.triggered.connect(MainWindow.showtools)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "表面缺陷检测系统V2.1"))
        self.groupBox_6.setTitle(_translate("MainWindow", "侧面检测图像"))
        self.groupBox_2.setTitle(_translate("MainWindow", "端面检测图像"))
        self.groupBox_3.setTitle(_translate("MainWindow", "检测计算结果"))
        self.label.setText(_translate("MainWindow", "产品型号："))
        self.label_3.setText(_translate("MainWindow", "通信状态："))
        self.label_4.setText(_translate("MainWindow", " "))
        self.label_5.setText(_translate("MainWindow", " "))
        self.label_6.setText(_translate("MainWindow", "相机状态："))
        self.label_7.setText(_translate("MainWindow", " "))
        self.label_11.setText(_translate("MainWindow", " "))
        self.label_10.setText(_translate("MainWindow", " "))
        self.label_9.setText(_translate("MainWindow", " "))
        self.label_8.setText(_translate("MainWindow", " "))
        self.label_12.setText(_translate("MainWindow", "检测总数："))
        self.label_13.setText(_translate("MainWindow", "不 合格 数："))
        self.label_14.setText(_translate("MainWindow", "良 品 率："))
        self.label_15.setText(_translate("MainWindow", "端面不合格："))
        self.label_16.setText(_translate("MainWindow", "检测时间："))
        self.label_17.setText(_translate("MainWindow", "侧面不合格："))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "设置"))
        self.menu_3.setTitle(_translate("MainWindow", "视图"))
        self.menu_4.setTitle(_translate("MainWindow", "工具"))
        self.menu_5.setTitle(_translate("MainWindow", "帮助"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.pushButton_16.setText(_translate("MainWindow", "打开图像"))
        self.pushButton_18.setText(_translate("MainWindow", "灰度转换"))
        self.pushButton_13.setText(_translate("MainWindow", "阈值分割（OTSU）"))
        self.pushButton_14.setText(_translate("MainWindow", "形态学处理"))
        self.pushButton_15.setText(_translate("MainWindow", "特征提取"))
        self.groupBox.setTitle(_translate("MainWindow", "图像滤波"))
        self.pushButton_2.setText(_translate("MainWindow", "高通滤波"))
        self.pushButton_3.setText(_translate("MainWindow", "低通滤波"))
        self.pushButton_4.setText(_translate("MainWindow", "平滑滤波"))
        self.pushButton_5.setText(_translate("MainWindow", "锐化滤波"))
        self.groupBox_4.setTitle(_translate("MainWindow", "直方图统计"))
        self.pushButton_6.setText(_translate("MainWindow", "R"))
        self.pushButton_7.setText(_translate("MainWindow", "G"))
        self.pushButton_8.setText(_translate("MainWindow", "B"))
        self.groupBox_5.setTitle(_translate("MainWindow", "图像增强"))
        self.pushButton_9.setText(_translate("MainWindow", "伪彩色增强"))
        self.pushButton_10.setText(_translate("MainWindow", "真彩色增强"))
        self.pushButton_11.setText(_translate("MainWindow", "直方图均衡"))
        self.pushButton_12.setText(_translate("MainWindow", "HSV颜色模型"))
        self.pushButton_17.setText(_translate("MainWindow", "保存图像"))
        self.pushButton.setText(_translate("MainWindow", "清空图像"))
        self.actionexit.setText(_translate("MainWindow", "退出程序"))
        self.actionsetPicPath.setText(_translate("MainWindow", "选择图片路径文件夹"))
        self.actionchooseTemplate.setText(_translate("MainWindow", "选择模板图片"))
        self.actionsetParaments.setText(_translate("MainWindow", "参数设置"))
        self.actionmax.setText(_translate("MainWindow", "窗口最大化"))
        self.actionmin_2.setText(_translate("MainWindow", "窗口最小化"))
        self.actionsetSavePath.setText(_translate("MainWindow", "设置检测结果保存路径"))
        self.actionipconfig.setText(_translate("MainWindow", "IP设置"))
        self.actionhelp_2.setText(_translate("MainWindow", "帮助"))
        self.actionabout_2.setText(_translate("MainWindow", "关于"))
        self.actionsave.setText(_translate("MainWindow", "保存检测结果"))
        self.actionstart.setText(_translate("MainWindow", "开始检测"))
        self.actionstop.setText(_translate("MainWindow", "暂停检测"))
        self.actionsetValue.setText(_translate("MainWindow", "setValue"))
        self.actiondelay_time.setText(_translate("MainWindow", "设置延时时间"))
        self.actionmethod_side.setText(_translate("MainWindow", "detect_method_side"))
        self.actionmethod_side.setToolTip(_translate("MainWindow", "side_method"))
        self.actiontools.setText(_translate("MainWindow", "调试工具"))
        self.actiontools.setToolTip(_translate("MainWindow", "tools"))
        self.actionset_yzFf_duan.setText(_translate("MainWindow", "设置端面阈值分割方法和阈值"))
        self.actionset_yzFf_ce.setText(_translate("MainWindow", "设置侧面阈值分割方法和阈值"))

import about_rc
import ce_yuzhiMethod_rc
import choose_rc
import delay_time_rc
import detect_methods_rc
import duan_yuzhiMethod_rc
import exit_rc
import green_circle_rc
import help_rc
import max_windows_rc
import min_windows_rc
import red_circle_rc
import save_rc
import set_ip_rc
import set_paraments_rc
import set_pic_path_rc
import set_value_rc
import start_rc
import stop_system_rc
import template_rc
import tools_rc
import yello_circle_rc
