# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '检测设置界面对话框0727.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import json
import multiprocessing
from ui_mainwindow import Ui_MainWindow
from PyQt5.QtGui import QIcon
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QCoreApplication
from PyQt5.QtWidgets import QApplication, QMainWindow, QMessageBox

global directory
directory = "C:/Users/Tu_Qiuping/Desktop/software_demo/"
global template
template = "C:/Users/Tu_Qiuping/Desktop/software_demo/"
global value_duan
value_duan = 70
global value_ce
value_ce = 38
global min_duan
min_duan = 120
global min_ce
min_ce = 120
global remove_ce
remove_ce = 38
global sample
sample = 0
global detect_model
detect_model = 0
global delay_time
delay_time = 0.5


class Ui_Dialog(object):
    def setupUi1(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(632, 555)
        Dialog.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 251, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 251, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 90, 71, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(110, 90, 261, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(400, 90, 141, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.textEdit_2 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_2.setGeometry(QtCore.QRect(543, 90, 61, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(30, 150, 71, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.textEdit_3 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_3.setGeometry(QtCore.QRect(110, 150, 121, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.textEdit_3.setFont(font)
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(397, 150, 141, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.textEdit_4 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_4.setGeometry(QtCore.QRect(540, 150, 61, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.textEdit_4.setFont(font)
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_5 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_5.setGeometry(QtCore.QRect(250, 150, 121, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.textEdit_5.setFont(font)
        self.textEdit_5.setObjectName("textEdit_5")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(20, 260, 71, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(20, 310, 71, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(100, 260, 441, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_2.setGeometry(QtCore.QRect(100, 310, 441, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(540, 260, 61, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(540, 310, 61, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 200, 271, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(330, 200, 271, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(360, 500, 101, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(500, 500, 101, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(270, 10, 331, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(20, 420, 211, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.radioButton = QtWidgets.QRadioButton(Dialog)
        self.radioButton.setGeometry(QtCore.QRect(170, 450, 111, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_2.setGeometry(QtCore.QRect(340, 450, 111, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(20, 370, 211, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.textEdit_6 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_6.setGeometry(QtCore.QRect(240, 370, 361, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.textEdit_6.setFont(font)
        self.textEdit_6.setObjectName("textEdit_6")

        self.retranslateUi(Dialog)
        self.pushButton.clicked.connect(Dialog.show_picpath)
        self.pushButton_2.clicked.connect(Dialog.show_templatepath)
        self.pushButton_3.clicked.connect(Dialog.set_value)
        self.pushButton_4.clicked.connect(Dialog.get_value)
        self.pushButton_5.clicked.connect(Dialog.yes)
        self.pushButton_6.clicked.connect(QCoreApplication.instance().quit)
        self.comboBox.currentIndexChanged['QString'].connect(Dialog.get_state)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def yes(self):
        global directory
        global template
        global value_duan
        global value_ce
        global min_duan
        global min_ce
        global remove_ce
        global sample
        global detect_model
        global delay_time
        if self.radioButton.isChecked():
            detect_model = 0
        if self.radioButton_2.isChecked():
            detect_model = 1
        delay_time = self.textEdit_6.toPlainText()
        dicts = {'directory': str(directory),
                 'template': str(template),
                 'value_duan': str(value_duan),
                 'value_ce': str(value_ce),
                 'min_duan': str(min_duan),
                 'min_ce': str(min_ce),
                 'remove_ce': str(remove_ce),
                 'sample': str(sample),
                 'delay_time': str(delay_time),
                 'detect_model': str(detect_model)}
        json_str = json.dumps(dicts)
        with open('./paraments/paraments.json', 'w') as json_file:
            json_file.write(json_str)
        return directory, template, value_ce, value_duan, min_ce, min_duan, remove_ce, sample, detect_model, delay_time

    def get_state(self):
        global sample
        state = self.comboBox.currentText()
        if state == '样品1':
            sample = 1
        if state == '样品2':
            sample = 2
        if state == '样品3':
            sample = 3
        if state == '样品4':
            sample = 4
        if state == '样品5':
            sample = 5
        return sample

    def show_picpath(self):
        global directory
        directory = QtWidgets.QFileDialog.getExistingDirectory(None, '选取文件夹', 'C:/')
        self.textBrowser.setText(directory)
        return directory

    def show_templatepath(self):
        global template
        template = QtWidgets.QFileDialog.getExistingDirectory(None, '选取文件夹', 'C:/')
        # template = QtWidgets.QFileDialog.getOpenFileName(self, '选择模板图片', 'C:/',
        #                                                  'All Files(*);;jpg Files(*.jpg);;bmp Files(*.bmp)')
        # template = template[0]
        self.textBrowser_2.setText(template)
        return template

    def set_value(self):
        global value_duan
        global value_ce
        global min_duan
        global min_ce
        global remove_ce
        value_duan = self.textEdit.toPlainText()
        min_duan = self.textEdit_2.toPlainText()
        value_ce = self.textEdit_3.toPlainText()
        min_ce = self.textEdit_4.toPlainText()
        remove_ce = self.textEdit_5.toPlainText()
        if value_ce == '' or value_duan == '' or min_ce == '' or min_duan == '' or remove_ce == '':
            QMessageBox.critical(self, '错误', '参数不可为空', QMessageBox.Yes)
            value_duan, value_ce, min_duan, min_ce, remove_ce = 70, 38, 120, 120, 38
        else:
            return value_duan, min_duan, value_ce, min_ce, remove_ce

    def get_value(self):
        self.textEdit.setText(str(value_duan))
        self.textEdit_2.setText(str(min_duan))
        self.textEdit_3.setText(str(value_ce))
        self.textEdit_4.setText(str(min_ce))
        self.textEdit_5.setText(str(remove_ce))

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "检测参数设置"))
        self.label.setText(_translate("Dialog", "请选择需要检测得样品型号："))
        self.label_2.setText(_translate("Dialog", "请设置检测参数："))
        self.label_3.setText(_translate("Dialog", "端面阈值："))
        self.label_4.setText(_translate("Dialog", "端面最小缺陷阈值："))
        self.label_5.setText(_translate("Dialog", "侧面阈值："))
        self.label_6.setText(_translate("Dialog", "侧面最小缺陷阈值："))
        self.label_7.setText(_translate("Dialog", "图片路径："))
        self.label_8.setText(_translate("Dialog", "模板路径："))
        self.pushButton.setText(_translate("Dialog", "浏览"))
        self.pushButton_2.setText(_translate("Dialog", "浏览"))
        self.pushButton_3.setText(_translate("Dialog", "设置参数"))
        self.pushButton_4.setText(_translate("Dialog", "获取参数"))
        self.pushButton_5.setText(_translate("Dialog", "确定"))
        self.pushButton_6.setText(_translate("Dialog", "关闭"))
        self.comboBox.setItemText(0, _translate("Dialog", "样品1"))
        self.comboBox.setItemText(1, _translate("Dialog", "样品2"))
        self.comboBox.setItemText(2, _translate("Dialog", "样品3"))
        self.comboBox.setItemText(3, _translate("Dialog", "样品4"))
        self.comboBox.setItemText(4, _translate("Dialog", "样品5"))
        self.label_9.setText(_translate("Dialog", "请选择检测模式："))
        self.radioButton.setText(_translate("Dialog", "在线检测"))
        self.radioButton_2.setText(_translate("Dialog", "离线检测"))
        self.label_10.setText(_translate("Dialog", "请设置循环延时时间(s)："))


class MyMainWindow_dialog(QMainWindow, Ui_Dialog):
    def __init__(self, parent=None):
        super(MyMainWindow_dialog, self).__init__(parent)
        self.setupUi1(self)


if __name__ == "__main__":
    multiprocessing.freeze_support()
    app = QApplication(sys.argv)
    app.setWindowIcon(QIcon('./gui/Icon.png'))
    myWin = MyMainWindow_dialog()
    myWin.show()
    sys.exit(app.exec())
