# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'load.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_load(object):
    def setupUi(self, load):
        load.setObjectName("load")
        load.resize(761, 544)
        load.setMaximumSize(QtCore.QSize(800, 600))
        self.frame = QtWidgets.QFrame(load)
        self.frame.setGeometry(QtCore.QRect(0, -10, 801, 571))
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_pic = QtWidgets.QLabel(self.frame)
        self.label_pic.setGeometry(QtCore.QRect(250, 80, 251, 251))
        self.label_pic.setText("")
        self.label_pic.setPixmap(QtGui.QPixmap("./gui/zjipc.png"))
        self.label_pic.setScaledContents(True)
        self.label_pic.setObjectName("label_pic")
        self.label_pic.show()
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setGeometry(QtCore.QRect(80, 380, 611, 51))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_hit = QtWidgets.QLabel(self.frame)
        self.label_hit.setGeometry(QtCore.QRect(340, 440, 201, 20))
        self.label_hit.setObjectName("label_hit")
        self.label_designer = QtWidgets.QLabel(self.frame)
        self.label_designer.setGeometry(QtCore.QRect(606, 520, 131, 20))
        self.label_designer.setObjectName("label_designer")

        self.retranslateUi(load)
        QtCore.QMetaObject.connectSlotsByName(load)

    def retranslateUi(self, load):
        _translate = QtCore.QCoreApplication.translate
        load.setWindowTitle(_translate("load", "Zjipc"))
        self.label_hit.setText(_translate("load", "资源加载中......"))
        self.label_designer.setText(_translate("load", "designed by zjipc"))
