# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/load.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import os
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_load(object):
    def setupUi(self, load):
        load.setObjectName("load")
        load.setWindowModality(QtCore.Qt.NonModal)
        load.resize(800, 600)
        load.setMaximumSize(QtCore.QSize(800, 600))
        self.frame = QtWidgets.QFrame(load)
        self.frame.setGeometry(QtCore.QRect(-10, -10, 881, 671))
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 801, 601))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.label_hit = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_hit.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hit.setObjectName("label_hit")
        self.gridLayout.addWidget(self.label_hit, 4, 0, 1, 5)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 4, 1, 1)
        self.label_pic = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_pic.setMinimumSize(QtCore.QSize(320, 320))
        self.label_pic.setMaximumSize(QtCore.QSize(320, 320))
        self.label_pic.setText("")
        filepath=os.path.dirname(os.path.abspath(__file__))
        self.label_pic.setPixmap(QtGui.QPixmap(os.path.join(filepath,'gui','zjipc.png')))
        #self.label_pic.setPixmap(QtGui.QPixmap('./gui/zjipc.png'))
        self.label_pic.setScaledContents(True)
        self.label_pic.setObjectName("label_pic")
        self.gridLayout.addWidget(self.label_pic, 1, 2, 1, 2)
        self.progressBar = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 45))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 2, 0, 1, 5)
        self.label_designer = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_designer.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_designer.setObjectName("label_designer")
        self.gridLayout.addWidget(self.label_designer, 6, 0, 1, 5)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 9, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 0, 1, 1)

        self.retranslateUi(load)
        QtCore.QMetaObject.connectSlotsByName(load)

    def retranslateUi(self, load):
        _translate = QtCore.QCoreApplication.translate
        load.setWindowTitle(_translate("load", "Zjipc"))
        self.label_hit.setText(_translate("load", "资源加载中......"))
        self.label_designer.setText(_translate("load", "designed by zjipc"))
        self.label.setText(_translate("load", " "))
        self.label_2.setText(_translate("load", " "))
